package com.tre3p.fileserver.util;

import org.springframework.stereotype.Component;

import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;

@Component
public class RandomPasswordGenerator {

    private static final int PASSWORD_LENGTH = 40;

    /**
     * This method used for generation random password for each file which is gonna be zipped.
     * @return String which contains random generated bytes.
     * @throws NoSuchAlgorithmException
     */
    public String generateRandomPassword() throws NoSuchAlgorithmException {
        byte[] result = new byte[PASSWORD_LENGTH];
        SecureRandom.getInstanceStrong().nextBytes(result);
        return new String(result);
    }

}
